language: generic
sudo: required
dist: trusty
env:
  matrix:
  - ARCH=armv6
  - ARCH=x86
  global:
  - secure: czQ/UkSOwTNneErDwlJh8q6NlQKUb28DlEsFCRY+9YGSt57oSHeuQ6GyVLyC9kwzvtwqojKGrdKqO0xFplJLXEBA3m1LV3Otdnx+Pl6UG6gWL84l/oVHHFafx8fq6x4rwbWfAJaIQGeWJzjAodSNp7Q2ouHjenRSXzbv2d0qecIGacPcyWH6Z9Mz/2qHUhpCEpbQMmZC/+1Lf3T+TT4Etau887q6lP22l1j2wxlkBb+dUXZTEbcz4wQCliLH4Lhlqfyk9WK70Nv/spheg7/d4yKBfMYTz4t6g///9jaVkMh/CRO5aCNlxjTUU43DX0qJBrX5H2vLZxgwXRVRPESKBA3MJkHnuRZTk62yDk4aGKMUIJh1UFeweuuJjtUBQtoCtdVNDGggNaLHe1jE0Y2f/CK2eUtjz+8CefQ7xgaUsFou8x/OlRnS89QzH9PTC8QZoLSjGDPcslxC9QJAHE43uIGj/wpIxxfChQgFPmxmSj4bRJ8UgPTpOzafgP6hAcUTEYozx/P7Hv2NFurOugZnPSF6xjf5KlS2ckxCyBrt6qVs0Yp0o73E3Mveu9HBklLWOqbxaMKpEPLgzysQJvOFHaQyOu7TzV48scYNmEAYruV8pR0WLuJOiwlet5dlxYBv9MwtP0jQJeADxoxPlLn6McXjHvxUL2x89aHZHAEIXGE=
  - secure: ly/hvhVYzS3HS4v2Ge6yg3D+DHNmvnW4YcCsHmRGKVLe2+Kkkv/KjweczKppjO++GXwOOHfwqbkUjJ5wrgimxOqXXXSbyFT/gh0wXBugoiVbyNb1JD6A15Q7Kec8FMvaiMRY6bcYUkreo0ktuZlueGiXyZZmfV4/xkaCk8CWC7MNLhYytFo2Desy76ZZOMoVVdTrepicwqumZ5N3aH0ZThveY59T8FkSYTz2ag0xtesVYZTxOoJbwFygNNQ+vjXiseAGlSTDdW2T8Z/BGsFCBQWfTfYT4gmMDYeMX1YouqfApUajaH2He+wxcoNhwg2/9X2j/HFwwgSZo0LDGytckMk3uAQ3xkutno0NnOMIlRyubEiEkoJ4B1lHJJzlaAO1wF0T3OGsFLLupeL4GFjmb1ma5iQLEAQZMbdXYxm/sAG+aTNbxaWWwA/MDotU3L5mlp3zQBL0EKlYc3JVPeDRrYNjMDURGaMNOUzeZgUhb3XvxOTaYUHDQXDay2N4OODBm7QPsmedbXG/go7b41nw8AbEHpjrY98TM1hXvdVT64RaqDklz6P+A/GG3zsL2Ktr5gZEetLiuAgz776+R6ckqOUt17qPkPFxpXOWs22KzigQf+Y2xH2BDf26WngAY1byE6Vhbk6pF0PcwPBZt0Ed+1/4Jhbk+uNE3InHkFq8pZ8=
services:
- docker
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
install: true
script:
- make mk-image ARCH=$ARCH
- make mk-deployment VERSION=$TRAVIS_TAG
- make mk-testflow VERSION=$TRAVIS_TAG
deploy:
  - provider: script
    script: make pushtohub USER=$DOCKER_USER PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_BRANCH
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH =~ ^master|develop$"
  - provider: script
    script: make pushtohub USER=$DOCKER_USER PASS=$DOCKER_PASS ARCH=$ARCH TAG=$TRAVIS_TAG
    on:
      tags: true
      all_branches: true
  - provider: releases
    prerelease: true
    skip_cleanup: true
    file_glob: true
    api_key:
      secure: YpJxBxBafvXKTrs9UBRyscISNnn8jAp+FuQy1/YO2FtWg4AjAu7vT0KhSC7FQDqsy2LuYs0eo0auR29ZzMXa+pYFZxgCRWnG+cySW7g5CQ8CRVyB8J5cECDSvDj5P6FE+2vrfkGBX+tJ4FgH7jWNuY1yeHDPUQ6vMRcsdYi+n65+VgsFUk1gdnNCuP6UWFYcbXJqOA7cVr+VXa599P9diR8WsqQtdsnXC8nrs6IYrQsohw8PQ7eamkxCcLtfp0c17DscANTFRiaL4lbXIK1gnQMAyZkMUBEB4VznY5gY+4i6/XT4BD/bOm9Nbk7xRn69msqQmktab4QwMG6LXvRzOyE/Bq21n43Gbx3uvZJ3oyT1SWvUOkjedKc8uIqO/iGaSIiBsBBkHw+gtmQzNiIN+efclcy48cEw/5DwYJAVH/wOPf2ncOLgxrM3NaBNSLJGnfvSs9r7Dl88dSDR9+RSFHQcV1A86e08OsAhKJhF11a13Yru2RvdxipWEQvISOeBeMbKBqi7pbRI6nxVvcrvrDvlESNHFlX52MOucVZwjNwqRQZBW4sQ/QpvE+q9tWud6Z9ugQ2G4cdvZ2Y6IXklvSFbL9z4bh4yjz626KcTdGEz1Vt+4siV8HKLtq0FtYrsegou13xwMXHLyWZoSqjSHdQTqDvJWYqfkW3B2Spp4yw=
    file: "./*.zip"
    on:
      tags: true
      repo: elespejo/bypass
      all_branches: true
