language: generic
sudo: required
dist: trusty
env:
  - ARCH=armv6
  - ARCH=x86
  global:
    - secure: X3a4IZseDwh+HaBFqo6/ZS2VyhCbVLxU5758T1zIWJlye/cvMxEmC14EM3NzxCjZcVUIbaffBCMxj8fHn6bQDgx3+GtK87mwZle1l8JLO74za7INj31GHuFX++9MVAcbb/Ue68oh0qLBAB4UGVaYmSwFafPCh7HJzntmQLdWRBpF5/LcLKqMggbqfXPdMVUNqMAOj0N3kwO9dDGTFcZYj1kkS8LX+97kwWMLFmkdPawCInC2JraFHzThXQ6IuBgS8rVl7uwuWL2AFpdoQvni590mZvc22QDiOZREvG/xFO2H2YcCw8fOGrjrfUV733cqFabz1IyLC00Pgpn+SlSjFR7BrbKGUDTjmvutn+DWyB/WrJmJYsTgazf7lC42HSghIq7q0jBmTZPH6H5ewyuHTTo8S2AQigvhIKh3Myi8V5FhuI4h8Mssec6+nYQ5TFftBIQgVZkzpgX8GY+qD+yiIBP0rU3U5zBzSZkw4Izp9zel2qepjHoGW33SPqKW1Az9iMg9mUoPLCb5r150L+5OsMpX3eSGptOJdR/uCe8WGAnwjiwC1HHVNtyzHqFbSM3cxI0iX007GuKrjx9bHyX2N57dq52iG3mPGHF1yDiFl10tjv1WNbXkTnaQBL/BCOQUYLL4Bj2WQ7sMF6ao59OAGJ8Gi1aAM62gwL5k9Gvbc28=
    - secure: l09wqG8W1Fms2f5rsgPYHPAM+yZH9yJoKcwzOMa67nNK3oqOebcNR3jPKHGVe8cxo+O3EucNKlZxGciElGy8fh4esiV49VXZDUPk5nb6q9ud/py4CHkGYNPCGdS28szwTBAmp+oTzvabM7IQiEoTz1L0/Jd/gro4vYbN+uD/Xwu0q6tFsRLzSpq4NM+7+vTt0M/cL0VuKop9RH53VBLRazj7Os3KBwd76PsyGC79QVlFT1rrx70hDK+N3PaDYGtCHdilVp9qNlK7huBiuK0HbsLYr60f1rGSF8iJ55O13yivaRlZ9dfxJ6LKf4l3LToMsA4vinupnGCzPr6kyR97H5Ex4pOdQKVJNWXvSVDOn0xaPFYHjRCHH9CXmCEBRikTa8fOgVkUt2Pjn76B3wiSgZajdr2NeCCixX9xtoOOnfzD7YX25RRNr0U1Aa0WhD0NxabrmM9WSi+hW8KHRH4QURLpt7c32W8WrWmlb6agvPsmtyPz7T8N+tWxE22iFTvsc0zC/o1GYi5OJA7BmhFoWa5FjjBw7m+ERj88L6KbXP/kgG4qJmrLXc4sNfgGfoIjtw7oRWdV+EZmx/U+0hp+unwE4o/YsEpyiVfKFSHU+UCsc49l26Fzr2xQLuQzuVjsyi4kpRc0vF/1vTQDEh6/3Mv+UYxezL/uebWGVEIwWzI=

services:
  - docker
branches:
  only:
  - master
  - develop
  - "/^\\d+\\.\\d+(\\.\\d+)?(-\\S*)?$/"
before_install:
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
install: true

jobs:
  include:
    - stage: build docker images 
      script: ./build $ARCH
    - stage: push to docker hub
      deploy:
        - provider: script
          script: bash deploy.sh $DOCKER_USER $DOCKER_PASS $ARCH $TRAVIS_BRANCH 
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^master|develop$
        - provider: script
          script: bash deploy.sh $DOCKER_USER $DOCKER_PASS $ARCH $TRAVIS_TAG 
          on:
            tags: true
            all_branches: true
